services:
  frontend:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NODE_OPTIONS=--openssl-legacy-provider
      - REACT_APP_API_GATEWAY_URL=http://localhost:8000
    volumes:
      - ./web:/app
      - /app/node_modules
      - ./web/src/styles:/app/src/styles
    depends_on:
      - api-gateway
      - deck-service
      - quiz-service
    networks:
      - flash_deck_shared_network

  deck-service:
    container_name: deck_service
    build:
      context: ./services/deck_service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - "./services/deck_service:/app"
      - flash_deck_db_data:/app/db
    networks:
      - flash_deck_shared_network

  quiz-service:
    container_name: quiz_service
    build:
      context: ./services/quiz_service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - "./services/quiz_service:/app"
      - flash_deck_db_data:/app/db
    networks:
      - flash_deck_shared_network

  api-gateway:
    container_name: api_gateway
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api_gateway:/app
    networks:
      - flash_deck_shared_network
    depends_on:
      - deck-service
      - quiz-service

volumes:
  flash_deck_db_data:

networks:
  flash_deck_shared_network:
    external: true