version: "3"

services:
  frontend:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REACT_APP_BACKEND_URL=http://backend:5000
      - NODE_OPTIONS=--openssl-legacy-provider
    volumes:
      - ./web:/app
      - /app/node_modules
      - ./web/src/styles:/app/src/styles
    depends_on:
      - backend
    networks:
      - flash_deck_shared_network

  backend:
    container_name: service
    build:
      context: ./service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./service:/app
    networks:
      - flash_deck_shared_network

networks:
  flash_deck_shared_network:
    external: true