version: "3.8"

services:
  httpd-proxy-local:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CONFIG_FILE: ./vhosts.conf
    image: proxy-local:1.0
    container_name: proxy-local
    ports:
      - "80:80"
    networks:
      - flash_deck_shared_network

networks:
  flash_deck_shared_network:
    external: true